deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -t rsa 162.241.61.38 >> ~/.ssh/known_hosts
  script:
    - ssh -o StrictHostKeyChecking=no mrguin98@162.241.61.38 "cd public_html/svsc2/react; git pull"
